# import = [
#   "~/.config/alacritty/catppuccin-mocha.toml"
# ]
#
[mouse]
hide_when_typing = false

[window]
dynamic_title = true

[env]
TERM = "xterm-256color"

[window.padding]
x = 15
y = 15

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
style = "Regular"
